name: Port Kernel Commits

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs everyday at midnight

jobs:
  port_kernel_commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout base kernel source
      uses: actions/checkout@v2
      with:
        repository: <base_kernel_repo>
        ref: <base_branch> # Specify the branch you want to clone

    - name: Checkout port kernel source
      uses: actions/checkout@v2
      with:
        repository: <port_kernel_repo>
        ref: <port_branch> # Specify the branch you want to clone

    - name: Fetch commits from port kernel source
      run: git fetch --unshallow

    - name: Apply port kernel commits to base kernel
      run: |
        git remote add port_repo $GITHUB_WORKSPACE
        git fetch port_repo
        git cherry-pick $(git rev-list --reverse HEAD..port_repo/$GITHUB_SHA)

    - name: Zip modified kernel source
      run: zip -r modified_kernel_source.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: modified_kernel_source
        path: modified_kernel_source.zip
